export const SHOW_OVERLAY = 'SHOW_OVERLAY';
export const HIDE_OVERLAY = 'HIDE_OVERLAY';

export const CHANGE_COLOR = 'CHANGE_COLOR';

export const SHOW_ABOUT_MODAL = 'SHOW_ABOUT_MODAL';
export const SHOW_HELP_MODAL = 'SHOW_HELP_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const LOAD_US_STATES_DATA = 'LOAD_US_STATES_DATA';
export const CLEAR_MAP = 'CLEAR_MAP';
export const FETCH_CATEGORY_STATE_SUCCESS = 'FETCH_CATEGORY_STATE_SUCCESS';
export const FETCH_CATEGORY_STATE_ERROR = 'FETCH_CATEGORY_STATE_ERROR';
export const FETCH_CATEGORY_COUNTY_SUCCESS = 'FETCH_CATEGORY_COUNTY_SUCCESS';
export const FETCH_CATEGORY_COUNTY_ERROR = 'FETCH_CATEGORY_COUNTY_ERROR';
